package com.intest.road.pojo;

public class FieldRoadLand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_ROAD_LAND.ID
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_ROAD_LAND.LAND_NAME
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    private String landName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_ROAD_LAND.ROAD_ID
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    private Short roadId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_ROAD_LAND.ID
     *
     * @return the value of X_FIELD_ROAD_LAND.ID
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_ROAD_LAND.ID
     *
     * @param id the value for X_FIELD_ROAD_LAND.ID
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_ROAD_LAND.LAND_NAME
     *
     * @return the value of X_FIELD_ROAD_LAND.LAND_NAME
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    public String getLandName() {
        return landName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_ROAD_LAND.LAND_NAME
     *
     * @param landName the value for X_FIELD_ROAD_LAND.LAND_NAME
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    public void setLandName(String landName) {
        this.landName = landName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_ROAD_LAND.ROAD_ID
     *
     * @return the value of X_FIELD_ROAD_LAND.ROAD_ID
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    public Short getRoadId() {
        return roadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_ROAD_LAND.ROAD_ID
     *
     * @param roadId the value for X_FIELD_ROAD_LAND.ROAD_ID
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    public void setRoadId(Short roadId) {
        this.roadId = roadId;
    }
}