package com.intest.road.pojo;

public class FieldRoadLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_LOCATION.LAT
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_LOCATION.LNG
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_LOCATION.PID
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    private Short pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_LOCATION.GROUP_ID
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    private Short groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_LOCATION.SEQ
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_LOCATION.COORDINATE_TYPE
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    private Short coordinateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_LOCATION.LAT
     *
     * @return the value of X_FIELD_LOCATION.LAT
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_LOCATION.LAT
     *
     * @param lat the value for X_FIELD_LOCATION.LAT
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_LOCATION.LNG
     *
     * @return the value of X_FIELD_LOCATION.LNG
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_LOCATION.LNG
     *
     * @param lng the value for X_FIELD_LOCATION.LNG
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_LOCATION.PID
     *
     * @return the value of X_FIELD_LOCATION.PID
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public Short getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_LOCATION.PID
     *
     * @param pid the value for X_FIELD_LOCATION.PID
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public void setPid(Short pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_LOCATION.GROUP_ID
     *
     * @return the value of X_FIELD_LOCATION.GROUP_ID
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public Short getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_LOCATION.GROUP_ID
     *
     * @param groupId the value for X_FIELD_LOCATION.GROUP_ID
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public void setGroupId(Short groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_LOCATION.SEQ
     *
     * @return the value of X_FIELD_LOCATION.SEQ
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_LOCATION.SEQ
     *
     * @param seq the value for X_FIELD_LOCATION.SEQ
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_LOCATION.COORDINATE_TYPE
     *
     * @return the value of X_FIELD_LOCATION.COORDINATE_TYPE
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public Short getCoordinateType() {
        return coordinateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_LOCATION.COORDINATE_TYPE
     *
     * @param coordinateType the value for X_FIELD_LOCATION.COORDINATE_TYPE
     *
     * @mbggenerated Wed Nov 14 16:42:03 CST 2018
     */
    public void setCoordinateType(Short coordinateType) {
        this.coordinateType = coordinateType;
    }
}