package com.intest.road.pojo;

public class FieldRoad {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_ROAD.ID
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_ROAD.ROAD_NAME
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    private String roadName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column X_FIELD_ROAD.ROAD_TYPE
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    private Short roadType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_ROAD.ID
     *
     * @return the value of X_FIELD_ROAD.ID
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_ROAD.ID
     *
     * @param id the value for X_FIELD_ROAD.ID
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_ROAD.ROAD_NAME
     *
     * @return the value of X_FIELD_ROAD.ROAD_NAME
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    public String getRoadName() {
        return roadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_ROAD.ROAD_NAME
     *
     * @param roadName the value for X_FIELD_ROAD.ROAD_NAME
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    public void setRoadName(String roadName) {
        this.roadName = roadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column X_FIELD_ROAD.ROAD_TYPE
     *
     * @return the value of X_FIELD_ROAD.ROAD_TYPE
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    public Short getRoadType() {
        return roadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column X_FIELD_ROAD.ROAD_TYPE
     *
     * @param roadType the value for X_FIELD_ROAD.ROAD_TYPE
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    public void setRoadType(Short roadType) {
        this.roadType = roadType;
    }
}