package com.intest.road.mapper;

import com.intest.road.pojo.FieldRoad;
import com.intest.road.pojo.FieldRoadLand;
import java.util.List;

public interface FieldRoadLandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD_LAND
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD_LAND
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    int insert(FieldRoadLand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD_LAND
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    FieldRoadLand selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD_LAND
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    List<FieldRoadLand> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD_LAND
     *
     * @mbggenerated Tue Nov 13 13:41:11 CST 2018
     */
    int updateByPrimaryKey(FieldRoadLand record);

    /**
     * 删除所有
     * @return
     */
    int deleteAll();

    List<FieldRoadLand> selectByRoadId(Short roadId);
}