package com.intest.road.mapper;

import com.intest.road.pojo.FieldRoad;
import java.util.List;

public interface FieldRoadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    int insert(FieldRoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    FieldRoad selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    List<FieldRoad> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table X_FIELD_ROAD
     *
     * @mbggenerated Tue Nov 13 13:41:10 CST 2018
     */
    int updateByPrimaryKey(FieldRoad record);

    /**
     * 删除所有
     * @return
     */
    int deleteAll();

    /**
     * 通过道路名称查询
     * @param roadName
     * @return
     */
    FieldRoad selectByRoadName(String roadName);

    /**
     * 通过道路类型查询
     * @param roadType
     * @return
     */
    List<FieldRoad> selectByRoadType(Short roadType);
}